name: AntiMinehut
version: '${version}'
main: me.improper.antiminehut.AntiMinehut
api-version: 1.17
authors: [ ImproperIssues ]
description: Disable and remove all minehut-relating plugins on your server!
website: https://github.com/ItziSpyder
permissions:
  antimh.commands.removeall:
    description: "Be able to delete all Minehut plugins and files through commands"
    default: op
commands:
  antiminehut:
    description: "Attempts to delete all Minehut plugins and files"
    usage: "/antimh <action>"
    permission: antimh.commands.removeall
    aliases:
      - antimh